from turtle import *

my_turtle = Turtle()
my_turtle.speed(0)
my_turtle.screen.setup(1200, 800)

def draw(t):
    t.right(90)
    t.forward(100)
    t.right(45)
    t.forward(100)
    t.backward(100)
    t.left(90)
    t.forward(100)
    t.up()
    t.goto(0,0)
    t.down()
    t.forward(50)
    t.backward(50)
    t.right(90)
    t.forward(50)
    t.goto(0,0)
    t.left(135)
    t.circle(50)
    t.up()
    t.goto(20,50)
    t.down()
    t.circle(10)
    t.up()
    t.goto(-20,50)
    t.down()
    t.circle(10)
    t.up()
    t.goto(-30,40)
    t.down()
    t.right(90)
    t.circle(30,180)
    t.ht()

draw(my_turtle)

# необходимо, чтобы окно не закрывалось само, а только по клику
my_turtle.screen.exitonclick()
my_turtle.screen.mainloop()